apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: flask-backend
        image: prateekbaba05/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URI
            value: pg-service
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password


---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
